locale: fa-IR
title: نوت‌بوک تکنولوژی زهرا
description: یادداشت‌ها، پروژه‌ها و تجربه‌ها در دنیای ابزار دقیق و الکترونیک

baseurl: "" 
url: "https://thetechnotez.github.io"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

author:
  name: "Zahra"
  avatar: "/assets/images/avatar.png"
  bio: "Instrumentation Systems Designer | Learning FPGA | Writing my notes here."

# Build settings
markdown: kramdown
highlighter: rouge

# SEO
logo: "/assets/images/logo.png"
